export const IMAGE_LOADING = "IMAGE_LOADING";
export const LOAD_THUMNAIL_IMAGE_LINK = "LOAD_THUMNAIL_IMAGE_LINK";
export const LOAD_CATEGOTY_IMAGE_LINK = "LOAD_CATEGORY_IMAGE_LINK";
export const CATEGORY_ROUTE_ENABLE = "CATEGORY_ROUTE_ENABLE";
export const CATEGORY_ROUTE_DISABLE = "CATEGORY_ROUTE_DISABLE";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CLEAR_TEMP_CMNTS = "CLEAR_TEMP_CMNTS";

export const CURRENT_USERNAME = "CURRENT_USERNAME";


export const CMNT_LOADING = "CMNT_LOADING";
export const CMNT_SUCCESS = "CMNT_SUCCESS";
export const TEMPORARY_CMNTS = "TEMPORARY_COMNTS";
export const USER_SUCCESS = "USER_SUCCESS";







export const JUNGLE_LINKS = "JUNGLE_LINKS";
export const OCEAN_LINKS = "OCEAN_LINKS";
export const HILL_LINKS = "HILL_LINKS";
export const SUNSET_LINKS = "SUNSET_LINKS";
export const WATERFALL_LINKS = "WATERFALL_LINKS";